name: Build OpenTelemetry Distribution
on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Package
        uses: "observIQ/otel-distro-builder@v1.0.7"
