name: Build OpenTelemetry Distribution
on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # For goreleaser
          fetch-depth: 0
      - name: Build and Package
        uses: "observIQ/otel-distro-builder@fix-snapshot-template"
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/artifacts/*
