name: Build OpenTelemetry Distribution
on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Package
        uses: "observIQ/otel-distro-builder@c722b95438ce0cb8e71fa13d842b7f4c4c567a08"
